export const METRO_STOP_NAMES = [
  "Edgbaston Village",
  "Five Ways",
  "Brindleyplace",
  "Library",
  "Town Hall",
  "Grand Central",
  "Corporation Street",
  "Bull Street",
  "St Chads",
  "St Paul's",
  "Jewellery Quarter",
  "Soho Benson Road",
  "Winson Green",
  "Handsworth Booth Street",
  "The Hawthorns",
  "Kenrick Park",
  "Trinity Way",
  "West Bromwich Central",
  "Lodge Road",
  "Dartmouth Street",
  "Dudley Street Guns Village",
  "Black Lake",
  "Wednesbury Great Western Street",
  "Wednesbury Parkway",
  "Bradley Lane",
  "Loxdale",
  "Bilston Central",
  "The Crescent",
  "Priestfield",
  "The Royal",
  "Pipers Row",
  "Wolverhampton Station",
  "Wolverhampton St George's",
];
